# New Version
language: java
jdk:
 - oraclejdk8

mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: lippep-spring-boot-test


# Depricated Version
#language: java

# Install with Maven
#mvn install -DskipTests -fn -quiet

# Test with Maven
#mvn test -B