# New Version
language: java
jdk:
 - oraclejdk8

script:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# Update to real values
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: fact-racing-name
