# New Version
# Can test file with "http://lint.travis-ci.org/"
language: java
jdk:
 - oraclejdk8

addons:
  sonarqube:
    organization: $sonar_org
    token:
      secure: $sonar_key
    branches:
      - master
      - develop

script:
 - mvn clean install -B -V
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

#after_success:
#- if [ "$TRAVIS_BRANCH" == "master" ]; then
  # deploy

# Update to real values
deploy:
 provider: heroku
 api-key:
  secure: $heroku_key
 app: $heroku_app