# New Version
language: java
jdk:
 - oraclejdk8

script:
 - mvn clean install -B -V
 - mvn sonar:sonar

 after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
  # deploy

# Update to real values
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: factracing
